export const CHECK_ADD_NEW_VIDEO = 'AddPostForm/CHECK_ADD_NEW_VIDEO'
export const CHECK_ADD_NEW_VIDEO_SUCCESS = 'AddPostForm/CHECK_ADD_NEW_VIDEO_SUCCESS'
export const CHECK_ADD_NEW_VIDEO_FAILURE = 'AddPostForm/CHECK_ADD_NEW_VIDEO_FAILURE'
export const CHECK_ADD_NEW_VIDEO_DUPLICATE = 'AddPostForm/CHECK_ADD_NEW_VIDEO_DUPLICATE'
