export const CHECK_ADD_NEW_VIDEO = 'AddPostForm/CHECK_ADD_NEW_VIDEO'
export const CHECK_ADD_NEW_VIDEO_SUCCESS = 'AddPostForm/CHECK_ADD_NEW_VIDEO_SUCCESS'
export const CHECK_ADD_NEW_VIDEO_FAILURE = 'AddPostForm/CHECK_ADD_NEW_VIDEO_FAILURE'

export const BACK_TO_HOME_PAGE = 'AddPostForm/BACK_TO_HOME_PAGE'
