export const ADD_POST_COMMENT = 'CommentForm/ADD_POST_COMMENT';
export const ADD_POST_COMMENT_SUCCESS = 'CommentForm/ADD_POST_COMMENT_SUCCESS';
export const ADD_COMMENT_REPLY = 'CommentForm/ADD_COMMENT_REPLY';
export const ADD_COMMENT_REPLY_SUCCESS = 'CommentForm/ADD_COMMENT_REPLY_SUCCESS';