export const LOAD_RECOMMENDATIONS = 'UpNext/LOAD_RECOMMENDATIONS';  
export const LOAD_RECOMMENDATIONS_SUCCESS = 'UpNext/LOAD_RECOMMENDATIONS_SUCCESS';  

export const LOAD_MORE_RECOMMENDATIONS = 'UpNext/LOAD_MORE_RECOMMENDATIONS';  
export const LOAD_MORE_RECOMMENDATIONS_SUCCESS = 'UpNext/LOAD_MORE_RECOMMENDATIONS';  
