import { LOGIN_MODAL_CLOSE, LOGIN_MODAL_OPEN } from '../App/constants'

const LIKE_POST = 'Like/LIKE_POST'
const LIKE_POST_SUCCESS = 'Like/LIKE_POST_SUCCESS'

const UNLIKE_POST = 'Like/UNLIKE_POST'
const UNLIKE_POST_SUCCESS = 'Like/UNLIKE_POST_SUCCESS'


export { LIKE_POST, LIKE_POST_SUCCESS, UNLIKE_POST, UNLIKE_POST_SUCCESS, LOGIN_MODAL_CLOSE, LOGIN_MODAL_OPEN }