import { SELECT_SIDEBAR_ITEM } from '../Sidebar/constants'

const LOGIN_REQUEST = 'App/LOGIN_REQUEST';
const LOGIN_SUCCESS = 'App/LOGIN_SUCCESS';

const LOGIN_MODAL_OPEN = 'App/LOGIN_MODAL_OPEN';
const LOGIN_MODAL_CLOSE = 'App/LOGIN_MODAL_CLOSE';

const LOGOUT_REQUEST = 'App/LOGOUT_REQUEST'
const TIMED_LOGOUT_REQUEST = 'App/TIMED_LOGOUT_REQUEST'
const LOGOUT_SUCCESS = 'App/LOGOUT_SUCCESS'

const ADD_SUBSCRIPTION = 'App/ADD_SUBSCRIPTION'
const ADD_SUBSCRIPTION_SUCCESS = 'App/ADD_SUBSCRIPTION_SUCCESS'

const SEARCH_POSTS = 'App/SEARCH_POSTS'
const SEARCH_POSTS_SUCCESS = 'App/SEARCH_POSTS_SUCCESS'

const LOAD_FEED_TOPICS = 'App/LOAD_FEED_TOPICS'
const LOAD_FEED_TOPICS_SUCCESS = 'App/LOAD_FEED_TOPICS_SUCCESS'

const LOAD_TAG_TOPICS = 'App/LOAD_TAG_TOPICS'
const LOAD_TAG_TOPICS_SUCCESS = 'App/LOAD_TAG_TOPICS_SUCCESS'

const HANDLE_HEAD_SECTION_DISMISS = 'App/HANDLE_HEAD_SECTION_DISMISS'
const LOAD_USER_PREFERENCES = 'App/LOAD_USER_PREFERENCES'

export {
    LOGIN_REQUEST, LOGIN_SUCCESS,
    LOGIN_MODAL_CLOSE, LOGIN_MODAL_OPEN,
    SELECT_SIDEBAR_ITEM,
    LOGOUT_REQUEST, LOGOUT_SUCCESS, TIMED_LOGOUT_REQUEST,
    ADD_SUBSCRIPTION, ADD_SUBSCRIPTION_SUCCESS,
    SEARCH_POSTS, SEARCH_POSTS_SUCCESS,
    LOAD_FEED_TOPICS, LOAD_FEED_TOPICS_SUCCESS,
    LOAD_TAG_TOPICS, LOAD_TAG_TOPICS_SUCCESS,
    HANDLE_HEAD_SECTION_DISMISS,
    LOAD_USER_PREFERENCES
}