import { SELECT_SIDEBAR_ITEM } from '../Sidebar/constants'

const LOGIN_REQUEST = 'App/LOGIN_REQUEST';

const LOGIN_SUCCESS = 'App/LOGIN_SUCCESS';

const LOGIN_MODAL_OPEN = 'App/LOGIN_MODAL_OPEN';

const LOGIN_MODAL_CLOSE = 'App/LOGIN_MODAL_CLOSE';

export { LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_MODAL_CLOSE, LOGIN_MODAL_OPEN, SELECT_SIDEBAR_ITEM }