import { LOGIN_SUCCESS, LOGIN_REQUEST, LOGIN_MODAL_CLOSE, LOGIN_MODAL_OPEN } from '../App/constants'
const CHANGE_SELECTION = 'Header/CHANGE_SELECTION';

export { LOGIN_SUCCESS, CHANGE_SELECTION, LOGIN_REQUEST, LOGIN_MODAL_CLOSE, LOGIN_MODAL_OPEN }