import {
    LOGIN_MODAL_CLOSE, LOGIN_MODAL_OPEN,
    LOGOUT_REQUEST, LOGOUT_SUCCESS
} from '../App/constants'
const CHANGE_SELECTION = 'Header/CHANGE_SELECTION';

export const PROFILE_REQUEST = 'Header/PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'Header/PROFILE_SUCCESS'

export const SETTINGS_REQUEST = 'Header/SETTINGS_REQUEST'
export const SETTINGS_SUCCESS = 'Header/SETTINGS_SUCCESS'

export {
    CHANGE_SELECTION,
    LOGIN_MODAL_OPEN, LOGIN_MODAL_CLOSE,
    LOGOUT_REQUEST, LOGOUT_SUCCESS
}